
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-10
owner: ucsb-cs156-f25
repo_name: team02-f25-10
pull_requests: [{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-index-Articles","number":132,"title":"Charlie index articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/132"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-edit-Articles","number":131,"title":"Charlie edit articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/131"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-create-Articles","number":130,"title":"Charlie create articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/130"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-pages-placeholder-Articles","number":129,"title":"Charlie pages placeholder articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/129"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-tables-Articles","number":108,"title":"Charlie tables articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/108"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-components-Articles","number":101,"title":"did the form component for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/101"}]
