
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-10
owner: ucsb-cs156-f25
repo_name: team02-f25-10
pull_requests: [{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-MenuItemReview-E2E","number":128,"title":"MenuItemReview: End to End Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/128"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-end-end","number":127,"title":"RecommendationRequest Added End to End Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/127"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-endToEndTest","number":126,"title":"UCSBDiningCommonsMenuItem End to End Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/126"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"sp-UCSBOrganization-e2eTests","number":125,"title":"UCSBOrganization: end to end tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/125"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-tables-Articles","number":108,"title":"Charlie tables articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/108"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-components-Articles","number":101,"title":"did the components for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/101"}]
