
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-10
owner: ucsb-cs156-f25
repo_name: team02-f25-10
pull_requests: [{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-components-Articles","number":101,"title":"did the components for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/101"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-edit-page","number":100,"title":"RecommendationRequest Edit Page + Tests and Storybook","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/100"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-editPage","number":99,"title":"UCSBDiningCommonsMenuItem Edit Page","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/99"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-Helprequest-edit-page","number":98,"title":"HelpRequest: Implement Edit Page, tests, and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/98"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-index-page","number":96,"title":"RecommendationRequest Index Page + Tests, Stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/96"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-indexPage","number":95,"title":"UCSBDiningCommonsMenuItem Index Page","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/95"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"sp-UCSBOrganization-editPage","number":94,"title":"UCSBOrganization: Edit page with tests and stories","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/94"}]
