
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-10
owner: ucsb-cs156-f25
repo_name: team02-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-integrationTest","number":122,"title":"UCSBDiningCommonsMenuItem Integration Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/122"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-integration-test","number":121,"title":"RecommendationRequest Added Integration Test - Testing the POST endpoint","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/121"},{"author":{"id":"MDQ6VXNlcjU1OTMwMzMy","is_bot":false,"login":"saanvi25","name":"Saanvi Pabbichetty"},"headRefName":"sp-UCSBOrganization-integrationTests","number":120,"title":"UCSBOrganization integration tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/120"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-HelpRequest-integration","number":119,"title":"HelpRequest: Create Integration Tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/119"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-tables-Articles","number":108,"title":"Charlie tables articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/108"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-components-Articles","number":101,"title":"did the components for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/101"}]
