
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-10
owner: ucsb-cs156-f25
repo_name: team02-f25-10
pull_requests: [{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-create-fixture","number":69,"title":"RecommendationRequest Create Fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/69"},{"author":{"id":"MDQ6VXNlcjMwMDI4NDg4","is_bot":false,"login":"Cobalt396","name":"Joseph Neamati"},"headRefName":"jn-RecommendationRequest-copy-backend","number":68,"title":"Added CRUD Backend files for RecommendationRequest from team01","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/68"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-fixtures","number":67,"title":"UCSBDiningCommonsMenuItem Fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/67"},{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-MenuItemReview-Fixtures","number":66,"title":"MenuItemReview Fixtures","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/66"},{"author":{"id":"U_kgDOCq2YEQ","is_bot":false,"login":"Gupperfisher","name":""},"headRefName":"charlie-fixtures-Articles","number":65,"title":"added team01 Articles files and fixtures for Articles","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/65"},{"author":{"id":"MDQ6VXNlcjcxMzU3MjUx","is_bot":false,"login":"Sarahbob","name":""},"headRefName":"sy-UCSBDiningCommonsMenuItem-copyBackend","number":64,"title":"Copied Backend from team01","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/64"},{"author":{"id":"MDQ6VXNlcjg1Mzk0OTI1","is_bot":false,"login":"Kham-arun","name":"Kham Arunsiriwongs"},"headRefName":"Kham-Helprequest-backend","number":63,"title":"HelpRequest: Copy all backend files from team01","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/63"},{"author":{"id":"U_kgDOCMvSuQ","is_bot":false,"login":"keigoomura","name":"Keigo Omura"},"headRefName":"Keigo-MenuItemReview-backend","number":62,"title":"Copying MenuItemReview backend files from Team01","url":"https://github.com/ucsb-cs156-f25/team02-f25-10/pull/62"}]
